### ISSUE TITLE
Codelst brokes in Typst 0.11.0-rc1

### ISSUE THREAD

**Issue by crd2333** [jneug/typst-codelst#11]
![1](https://github.com/jneug/typst-codelst/assets/113617021/87d43719-7b30-432d-87ce-48d8f876d639)
- The line numbers are gone.
- The highlighted lines are incorrect.
- Adding `numbers-start` gets the numbers come back but in a wrong way.

There may be more broken things to be tested.

**Comment by jneug** [comment]
Thanks to @kilpkonn I just submitted v2.0.1 to the package repository: https://github.com/typst/packages/pull/437
